# Generated by Django 4.1.1 on 2022-09-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='due_date',
            field=models.DateField(),
        ),
    ]
