# Generated by Django 4.1.1 on 2022-09-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activities_due_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activities',
            unique_together={('description', 'client_code')},
        ),
    ]
